In [5]:
%pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.11.1-cp313-cp313-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.63.0-cp313-cp313-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in c:\Users\omrka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\Users\omrka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=9 in c:\Users\omrka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\omrka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\omrka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\Users\omrka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.1-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.3 MB 6.3 MB/s eta 0:00:02
   ----------- ---------------------------- 2.6/9.3 MB 7.2 MB/s eta 0:00:01
   -------------------- ------------------- 4.7/9.3 MB 8.3 MB/s eta 0:00:01
   ------------------------------- -------- 7.3/9.3 MB 9.4 MB/s eta 0:00:01
   -------------------------------- ------- 7.6/9.3 MB 8.6 MB/s eta 0:00:01
   ------------------------------------- -- 8.7/9.3 MB 7.4 MB/s eta 0:00:01
   ---------------------------------------  9.2/9.3 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 6.3 MB/s  0:00:01
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.3 MB 2.9 MB/s eta 0:00:01
   ------------- -------------------------- 0.8/2.3 MB 2.1 MB/s eta 0:00:01
   ----------------- ---------------------- 1.0/2.3 MB 2.1 MB/s eta 0:00:01
   ---------------------- ----------------- 1.3/2.3 MB 1.7 MB/s eta 0:00:01
   ------------------------------- -------- 1.8/2.3 MB 1.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 1.6 MB/s  0:00:01
Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl (73 kB)
Installing collected packages: kiwisolver, fonttools, cycler, contourpy, matplotlib

   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   ---------------- ----------------------- 2/5 [cycler]
   ------------------------ --------------- 3/5 [contourpy]
   ------------------------ --------------- 3/5 [contourpy]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   ---------------------------------------- 5/5 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.11.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [7]:
RAW_PATH = "../data/raw/des/des_apy_raw.csv"

df = pd.read_csv(RAW_PATH)

print("Shape:", df.shape)
df.head()

Shape: (455359, 17)

,_id,id,year,state_name,state_code,district_name,district_code,crop_name,crop_code,crop_type,season,area,area_unit,production,production_unit,yield,yield_unit
0,1,0,1997-1998,Andhra Pradesh,28,Ananthapuramu,502,Arhar/Tur,202.0,Pulses,Kharif,21400.0,Hectare,2600.0,Tonnes,0.121,Tonnes/Hectare
1,2,1,1997-1998,Andhra Pradesh,28,Ananthapuramu,502,Bajra,103.0,Cereals,Kharif,1400.0,Hectare,500.0,Tonnes,0.357,Tonnes/Hectare
2,3,2,1997-1998,Andhra Pradesh,28,Ananthapuramu,502,Castor Seed,1002.0,Oilseeds,Kharif,1000.0,Hectare,100.0,Tonnes,0.100,Tonnes/Hectare
3,4,3,1997-1998,Andhra Pradesh,28,Ananthapuramu,502,Cotton(Lint),1101.0,Fiber Crops,Kharif,7300.0,Hectare,9400.0,Tonnes,1.288,Tonnes/Hectare
4,5,4,1997-1998,Andhra Pradesh,28,Ananthapuramu,502,Dry Chillies,502.0,Spices,Kharif,3700.0,Hectare,7100.0,Tonnes,1.919,Tonnes/Hectare

In [8]:
#Inspecting Schema
print("Columns:")
for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

Columns:
1. _id
2. id
3. year
4. state_name
5. state_code
6. district_name
7. district_code
8. crop_name
9. crop_code
10. crop_type
11. season
12. area
13. area_unit
14. production
15. production_unit
16. yield
17. yield_unit

In [9]:
#Basic Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 455359 entries, 0 to 455358
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   _id              455359 non-null  int64
 1   id               455359 non-null  int64
 2   year             455359 non-null  object
 3   state_name       455359 non-null  object
 4   state_code       455359 non-null  int64
 5   district_name    455359 non-null  object
 6   district_code    455359 non-null  int64
 7   crop_name        455359 non-null  object
 8   crop_code        455338 non-null  float64
 9   crop_type        455359 non-null  object
 10  season           455359 non-null  object
 11  area             455359 non-null  float64
 12  area_unit        455359 non-null  object
 13  production       450350 non-null  float64
 14  production_unit  455359 non-null  object
 15  yield            455359 non-null  float64
 16  yield_unit       455359 non-null  object
dtypes: float64(4), int64(4), object(9)
memory usage: 59.1+ MB

In [ ]:
df.describe(include="all")

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
_id,455359.0,NaN,NaN,NaN,227680.0,131450.964951,1.0,113840.5,227680.0,341519.5,455359.0
id,455359.0,NaN,NaN,NaN,227679.0,131450.964951,0.0,113839.5,227679.0,341518.5,455358.0
year,455359,26,2019-2020,22186,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state_name,455359,34,Uttar Pradesh,56511,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state_code,455359.0,NaN,NaN,NaN,19.412593,9.430053,1.0,10.0,21.0,28.0,38.0
district_name,455359,737,Belagavi,1700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
district_code,455359.0,NaN,NaN,NaN,359.423745,185.52071,1.0,193.0,375.0,520.0,765.0
crop_name,455359,115,Rice,31636,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crop_code,455338.0,NaN,NaN,NaN,468.182563,368.573998,101.0,107.0,288.0,708.0,1503.0
crop_type,455359,10,Cereals,125657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
season,455359,7,Kharif,161402,NaN,NaN,NaN,NaN,NaN,NaN,NaN
area,455359.0,NaN,NaN,NaN,13130.019486,48466.551758,0.004,79.0,600.0,4777.0,8580100.0
area_unit,455359,1,Hectare,455359,NaN,NaN,NaN,NaN,NaN,NaN,NaN
production,450350.0,NaN,NaN,NaN,838031.983951,20286115.940013,0.0,91.0,808.0,8350.0,1597800000.0
production_unit,455359,1,Tonnes,455359,NaN,NaN,NaN,NaN,NaN,NaN,NaN
yield,455359.0,NaN,NaN,NaN,68.84521,861.71475,0.0,0.563,1.051,2.55,43958.333
yield_unit,455359,1,Tonnes/Hectare,455359,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Year coverage
year_counts = (
    df.groupby("year")
      .size()
      .reset_index(name="records")
      .sort_values("year")
)

display(year_counts)

         year  records
0   1997-1998    10445
1   1998-1999    13670
2   1999-2000    14329
3   2000-2001    14813
4   2001-2002    14406
5   2002-2003    17795
6   2003-2004    18436
7   2004-2005    15350
8   2005-2006    15239
9   2006-2007    16073
10  2007-2008    16094
11  2008-2009    16641
12  2009-2010    16975
13  2010-2011    16531
14  2011-2012    18128
15  2012-2013    17227
16  2013-2014    18618
17  2014-2015    18022
18  2015-2016    18473
19  2016-2017    19801
20  2017-2018    20556
21  2018-2019    20744
22  2019-2020    22186
23  2020-2021    21608
24  2021-2022    21350
25  2022-2023    21849

In [12]:
#State coverage
print("Number of states/UTs:",
      df["state_name"].nunique())

print("\nStates/UTs:")
print(sorted(df["state_name"].dropna().unique()))

Number of states/UTs: 34

States/UTs:
['Andaman And Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu And Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'The Dadra And Nagar Haveli And Daman And Diu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [13]:
#District Coverage
print("Number of districts:",
      df["district_name"].nunique())

print("Missing district names:",
      df["district_name"].isna().sum())

Number of districts: 737
Missing district names: 0

In [14]:
#Crop coverage
crop_summary = (
    df.groupby(["crop_name", "crop_type"])
      .agg(
          years=("year", "nunique"),
          records=("year", "size"),
          districts=("district_name", "nunique")
      )
      .sort_values("records", ascending=False)
)

display(crop_summary)

                             years  records  districts
crop_name         crop_type
Rice              Cereals       26    31636        722
Maize             Cereals       26    30781        724
Moong(Green Gram) Pulses        26    23419        685
Urad              Pulses        26    22104        681
Groundnut         Oilseeds      26    18623        600
...                            ...      ...        ...
Litchi            Fruits         2        6          5
Plums             Fruits         2        6          4
Apple             Fruits         2        4          2
Peach             Fruits         2        4          2
Other Dry Fruit   Fruits         1        1          1

[115 rows x 3 columns]

In [15]:
#Season Coverage
season_summary = (
    df.groupby("season")
      .agg(
          records=("year", "size"),
          crops=("crop_name", "nunique"),
          districts=("district_name", "nunique")
      )
      .sort_values("records", ascending=False)
)

display(season_summary)

            records  crops  districts
season
Kharif       161402     76        735
Rabi         120049     63        731
Whole Year    81403    100        691
Total         48044     58        677
Summer        26811     34        467
Winter         9616     27        229
Autumn         8034     24        248

In [16]:
#Missing value audit
missing = (
    df.isna()
      .sum()
      .reset_index()
      .rename(columns={
          "index": "column",
          0: "missing_count"
      })
)

missing["missing_percent"] = (
    missing["missing_count"] / len(df) * 100
)

display(
    missing.sort_values(
        "missing_count",
        ascending=False
    )
)

             column  missing_count  missing_percent
13       production           5009         1.100011
8         crop_code             21         0.004612
0               _id              0         0.000000
3        state_name              0         0.000000
1                id              0         0.000000
4        state_code              0         0.000000
5     district_name              0         0.000000
6     district_code              0         0.000000
2              year              0         0.000000
7         crop_name              0         0.000000
9         crop_type              0         0.000000
11             area              0         0.000000
10           season              0         0.000000
12        area_unit              0         0.000000
14  production_unit              0         0.000000
15            yield              0         0.000000
16       yield_unit              0         0.000000

In [17]:
#Duplicate check
key_columns = [
    "state_name",
    "district_name",
    "crop_name",
    "season",
    "year"
]

duplicates = df.duplicated(
    subset=key_columns,
    keep=False
)

print("Duplicate records:",
      duplicates.sum())

Duplicate records: 0

In [18]:
#Checking units
print("Area units:")
print(df["area_unit"].value_counts(dropna=False))

print("\nProduction units:")
print(df["production_unit"].value_counts(dropna=False))

print("\nYield units:")
print(df["yield_unit"].value_counts(dropna=False))

Area units:
area_unit
Hectare    455359
Name: count, dtype: int64

Production units:
production_unit
Tonnes    455359
Name: count, dtype: int64

Yield units:
yield_unit
Tonnes/Hectare    455359
Name: count, dtype: int64

HISOTRICAL CROP SUBSET OF THE MAIN DATASET

In [19]:
START_YEAR = "2013-2014"
END_YEAR = "2022-2023"

historical_df = df[
    df["year"].between(
        START_YEAR,
        END_YEAR
    )
].copy()

print("Historical dataset shape:",
      historical_df.shape)

print(
    historical_df["year"]
    .value_counts()
    .sort_index()
)

Historical dataset shape: (203207, 17)
year
2013-2014    18618
2014-2015    18022
2015-2016    18473
2016-2017    19801
2017-2018    20556
2018-2019    20744
2019-2020    22186
2020-2021    21608
2021-2022    21350
2022-2023    21849
Name: count, dtype: int64

In [ ]:
#Target crops for initial version
TARGET_CROPS = [
    "Rice",
    "Wheat",
    "Maize",
    "Jowar",
    "Bajra",
    "Ragi",
    "Soyabean",
    "Groundnut",
    "Cotton",
    "Gram",
    "Arhar/Tur",
    "Urad",
    "Sugarcane"
]

In [21]:
crop_df = historical_df[
    historical_df["crop_name"].isin(TARGET_CROPS)
].copy()

print("Selected crop dataset:",
      crop_df.shape)

print(
    crop_df["crop_name"]
    .value_counts()
)

Selected crop dataset: (85920, 17)
crop_name
Maize        14263
Rice         13989
Urad         10871
Groundnut     8446
Jowar         5830
Arhar/Tur     5819
Wheat         5303
Sugarcane     5055
Gram          4973
Bajra         4739
Ragi          3570
Soyabean      3062
Name: count, dtype: int64

In [23]:
#Standardizing numeric columns
numeric_columns = [
    "area",
    "production",
    "yield"
]

for col in numeric_columns:
    crop_df[col] = pd.to_numeric(
        crop_df[col],
        errors="coerce"
    )

crop_df[numeric_columns].describe()

                area    production         yield
count   85920.000000  8.572400e+04  85920.000000
mean    22132.375261  9.830196e+04      5.244610
std     52461.954120  6.638503e+05     15.803031
min         0.004000  0.000000e+00      0.000000
25%       154.000000  2.208625e+02      0.906000
50%      1674.000000  2.688000e+03      1.581000
75%     14930.250000  3.240000e+04      2.717000
max    997356.000000  3.028500e+07    599.000000

In [25]:
#Creating standardized units
crop_df["area_ha"] = crop_df["area"]

crop_df["production_tonnes"] = crop_df["production"]

crop_df["yield_tonnes_ha"] = crop_df["yield"]

crop_df["yield_kg_ha"] = (
    crop_df["yield_tonnes_ha"] * 1000
)

crop_df["yield_quintal_acre"] = (
    crop_df["yield_tonnes_ha"] * 10 / 2.47105
)

In [26]:
#Adding the source field
crop_df["data_source"] = "DES_APY"

In [27]:
#Selecting clean columns
FINAL_COLUMNS = [
    "state_name",
    "state_code",
    "district_name",
    "district_code",
    "crop_name",
    "crop_code",
    "crop_type",
    "season",
    "year",
    "area_ha",
    "production_tonnes",
    "yield_tonnes_ha",
    "yield_kg_ha",
    "yield_quintal_acre",
    "data_source"
]

crop_clean = crop_df[FINAL_COLUMNS].copy()

In [28]:
#Renaming them
crop_clean = crop_clean.rename(columns={
    "state_name": "state",
    "district_name": "district",
    "crop_name": "crop_source_name"
})

In [29]:
#Adding temporary standard crop name
crop_clean["crop"] = crop_clean["crop_source_name"]

In [30]:
#Arranging the columns
crop_clean = crop_clean[
    [
        "state",
        "state_code",
        "district",
        "district_code",
        "crop",
        "crop_source_name",
        "crop_code",
        "crop_type",
        "season",
        "year",
        "area_ha",
        "production_tonnes",
        "yield_tonnes_ha",
        "yield_kg_ha",
        "yield_quintal_acre",
        "data_source"
    ]
]

In [31]:
#Running the first quality checks
print("Final shape:", crop_clean.shape)

print("\nMissing values:")
print(
    crop_clean.isna().sum()
    .sort_values(ascending=False)
)

print("\nDuplicates:")
print(
    crop_clean.duplicated(
        subset=[
            "state",
            "district",
            "crop",
            "season",
            "year"
        ]
    ).sum()
)

Final shape: (85920, 16)

Missing values:
production_tonnes     196
state                   0
district                0
state_code              0
crop                    0
crop_source_name        0
crop_code               0
district_code           0
crop_type               0
season                  0
year                    0
area_ha                 0
yield_tonnes_ha         0
yield_kg_ha             0
yield_quintal_acre      0
data_source             0
dtype: int64

Duplicates:
0

In [32]:
#Checking for impossible values
print("Negative area:",
      (crop_clean["area_ha"] < 0).sum())

print("Negative production:",
      (crop_clean["production_tonnes"] < 0).sum())

print("Negative yield:",
      (crop_clean["yield_tonnes_ha"] < 0).sum())

Negative area: 0
Negative production: 0
Negative yield: 0

In [33]:
print(
    "Zero production:",
    (crop_clean["production_tonnes"] == 0).sum()
)

print(
    "Zero yield:",
    (crop_clean["yield_tonnes_ha"] == 0).sum()
)

Zero production: 105
Zero yield: 301

In [34]:
#Saving processed historical dataset
OUTPUT_PATH = (
    "../data/processed/crop_yield/"
    "des_apy_2013_14_2022_23.csv"
)

crop_clean.to_csv(
    OUTPUT_PATH,
    index=False
)

print("Saved:", OUTPUT_PATH)

Saved: ../data/processed/crop_yield/des_apy_2013_14_2022_23.csv